server:
  port: 8761

spring:
  application:
    name: discovery
  cloud:
    client:
      hostname: localhost

eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
  dashboard:
    enabled: true

---

spring:
  profiles: discovery1

server:
  port: 8761

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://127.0.0.1:8762/eureka/

---

spring:
  profiles: discovery2

server:
  port: 8762

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://127.0.0.1:8761/eureka/
