spring:
  application:
    name: TEST

server:
  port: 8761

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  server:
    waitTimeInMsWhenSyncEmpty: 0
  dashboard:
    enabled: false

management:
  security:
    enabled: false
