server:
    port: 8282

spring:
    application:
        name: discovery
    cloud:
        client:
            hostname: 127.0.0.1
            
eureka:
    client:
        registerWithEureka: false
        fetchRegistry: false
        healthcheck:
            enabled: true
        serviceUrl:
            defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
    server:
        enableSelfPreservation: true
        renewalPercentThreshold: 0.1
        waitTimeInMsWhenSyncEmpty: 0
    instance:
        hostname: 127.0.0.1
        preferIpAddress: true
    dashboard:
        enabled: true

management:
    security:
        enabled: false

endpoints:
    sensitive: false
    mappings:
        sensitive: false