server:
    port: 8282
--
spring:
    application:
        name: discovery
--
error:
    whitelabel:
        enabled: false
--
eureka:
    client:
        registerWithEureka: false
        fetchRegistry: false
        healthcheck:
            enabled: true
        serviceUrl:
            defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
    instance:
        hostname: localhost
    dashboard:
        enabled: true