server:
    port: 8181

spring:
    application:
        name: discovery
    cloud:
        client:
            hostname: localhost

eureka:
    client:
        registerWithEureka: true
        fetchRegistry: false
        healthcheck:
            enabled: true
    server:
        enableSelfPreservation: true
        renewalPercentThreshold: 0.1
        waitTimeInMsWhenSyncEmpty: 0
    instance:
        registryFetchIntervalSeconds: 3600
        leaseRenewalIntervalInSeconds: 3600
        preferIpAddress: true
    dashboard:
        enabled: true

management:
    security:
        enabled: false

endpoints:
    sensitive: false
    mappings:
        sensitive: false
   

http:
    mappers:
        json-pretty-print: true      
        
---

spring:
    profiles: discovery1

server:
    port: 8181

eureka:
    client:
        registerWithEureka: true
        fetchRegistry: false
        serviceUrl:
            defaultZone: http://127.0.0.1:8181/eureka/

---

spring:
    profiles: discovery2

server:
    port: 8282

eureka:
    client:
        registerWithEureka: true
        fetchRegistry: false
        serviceUrl:
            defaultZone: http://127.0.0.1:8282/eureka/
