server:
  port: 8761

spring:
  application:
    name: discovery
#  cloud:
#    client:
#      hostname: localhost

eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
  instance:
    hostname: localhost
  dashboard:
    enabled: true

---

spring:
  profiles: discovery1

eureka:
  instance:
    hostname: 8761
  client:
    serviceUrl:
      defaultZone: http://localhost:8762/eureka/

---

spring:
  profiles: discovery2

eureka:
  instance:
    hostname: 8762
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/