server:
  port: 8080

spring:
  application:
    name: gateway
  cloud:
    client:
      hostname: localhost

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    preferIpAddress: true

zuul:
  routes:
    discovery:
      path: /discovery/**
      sensitive-headers: Cookie,Set-Cookie,Authorization